package Lesson2;

public class ex2 {
    /*
    Задание 2 (исправленный код):

    try {
    int d = 0;
    double catchedRes1 = intArray[8] / d;
    System.out.println("catchedRes1 = " + catchedRes1);
} catch (ArithmeticException e) {
    System.out.println("Catching arithmetic exception: " + e);
} catch (ArrayIndexOutOfBoundsException e) {
    System.out.println("Catching array index out of bounds exception: " + e);
}
 */
}
